CREATE TABLE STUDENT(ID int, FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(255),CREATE_DATE DATE,UPDATE_DATE DATE,STATUS VARCHAR(226));

INSERT INTO STUDENT VALUES(123,'RUTIKA','GULHANE',SYSDATE(),SYSDATE(),'ACTIVE');
INSERT INTO STUDENT VALUES(345,'HEMA','PILLARI',SYSDATE(),SYSDATE(),'ACTIVE');
INSERT INTO STUDENT VALUES(5678,'HEMA','RAO',SYSDATE(),SYSDATE(),'ACTIVE');